### ISSUE TITLE
[과제 제출 관련] 안녕하세요! 프리온보딩 챌린지 관련 질문입니다.

### ISSUE THREAD

**Issue by YOOJS1205** [starkoora/wanted-pre-onboarding-challenge-fe-1-api#1]
안녕하세요! 원티드 프리온보딩 챌린지 신청했는데 8/6 (토)까지 과제를 바로 진행하면 되는건가요?
아니면 신청 이후 따로 선발을 기다려야 하는건가요?

**Comment by starkoora** [comment]
- 선발 절차는 없습니다-! 신청하신 누구나 참여 가능하며, 4번 강의에 전부 출석하신 분들을 대상으로 챌린지 시상을 진행하니 참고 부탁드립니다.
- 다만 이벤트 페이지에서 안내 드렸듯 코스 커리큘럼 자체가 사전 과제의 코드를 기반으로 진행될 예정이기 때문에 강의 시작 전까지는 미리 진행해두시는 걸 권장드립니다 :)
