### ISSUE TITLE
db.ts에 오타가 있습니다

### ISSUE THREAD

**Issue by RyeongeunKim** [starkoora/wanted-pre-onboarding-challenge-fe-1-api#14]
![image](https://user-images.githubusercontent.com/80612679/209424191-2ccde932-05de-4f2a-9767-d81f81e2fdf8.png)
 
실행 시 오류가 떠서 확인해보니 db.ts 45번째 줄에 오타가 있습니다. 
-> db.data ||= { todos: [], users: [] }; 
-> db.data = { todos: [], users: [] }; 이렇게 고치니까 실행됩니다.

**Comment by saengmotmi** [comment]
> ![image](https://user-images.githubusercontent.com/80612679/209424191-2ccde932-05de-4f2a-9767-d81f81e2fdf8.png)
> 
>  
> 
> 실행 시 오류가 떠서 확인해보니 db.ts 45번째 줄에 오타가 있습니다. 
> 
> -> db.data ||= { todos: [], users: [] }; 
> 
> -> db.data = { todos: [], users: [] }; 이렇게 고치니까 실행됩니다.
> 
> 
> 
> 
> 
> 
> 
> 

https://github.com/starkoora/wanted-pre-onboarding-challenge-fe-1-api/issues/7#issuecomment-1202088580 이 링크 확인해보시겠어요?

**Comment by RyeongeunKim** [comment]
node 최신 버전으로 다운로드 하니까 잘 됩니다. 감사합니다.
