### ISSUE TITLE
사전 미션 수행 마감기한

### ISSUE THREAD

**Issue by kokiok3** [starkoora/wanted-pre-onboarding-challenge-fe-1-api#17]
안녕하세요. 사전 미션 마감기한이 1월 5일까지 이던데 정해진 시간이 있나요?
제가 늦게 신청을 해서 1월 5일까지 완성하기에는 부족할 것 같은데 수업 시작(1월10일) 전 까지 완료해도 상관없나요,
아님 1월 5일 까지 완성을 해야지 검사를 받을 수 있는건가요?

**Comment by starkoora** [comment]
과제를 100% 완성하지 못하셔도 강의 진행하며 계속 보강할 것이기 때문에 상관없습니다. 다만 본인이 할 수 있는 최대한을 해본 후 강의를 들으며 고쳐나가는 것이 학습 효과가 가장 좋다고 생각합니다.
동일한 답변에 대한 링크 첨부합니다. https://github.com/starkoora/wanted-pre-onboarding-challenge-fe-1-api/issues/1#issuecomment-1196291510
