### ISSUE TITLE
사전미션 수행 GitHub 계정 관련 문의

### ISSUE THREAD

**Issue by ParkKyungChan** [starkoora/wanted-pre-onboarding-challenge-fe-1-api#21]
안녕하세요! 원티드 계정 이메일과 사전미션을 수행한 github 계정 이메일이 달라도 상관없을까요?
설문에 별도로 사전미션 수행 repo URL을 입력하는 칸이 없어서 문의드립니다.
아니면 제일 처음에 있는 이메일이 깃허브계정 이메일 적는 칸인가요?

**Comment by starkoora** [comment]
오리엔테이션에서 사전 미션을 받을 예정이라 괜찮을 것 같습니다 @ParkKyungChan
