### ISSUE TITLE
라이브러리 사용 관련 질문 있습니다.

### ISSUE THREAD

**Issue by Jang-oi** [starkoora/wanted-pre-onboarding-challenge-fe-1-api#3]
Axios, MUI 같은 라이브러리를 사용해도 상관 없는지 답변 부탁 드립니다!

**Comment by starkoora** [comment]
@Jang-oi  기본적으로 자유롭게 사용하시면 됩니다. 다만 사전 과제의 취지는 합 / 불합을 가리기 위함이 아니라
- 과제 수행 개수에 따라 기본적인 평가가 이루어지며, 커리큘럼 운영 과정에서 최소한의 수준을 파악하기 위함
- 코드의 일관성, 가독성, 함수 분리, 컴포넌트 설계, 코드 퀄리티 등을 기준으로 세부적으로 평가하기 위함

이고, 추후 이 코드를 수업 내용을 기반으로 함께 고쳐나갈 것이기 때문에 이 점을 참고하여 수행해주시면 감사하겠습니다. 너무 부담 갖지는 마세요 :)
