### ISSUE TITLE
서버관련 문의드립니다

### ISSUE THREAD

**Issue by SeungMiL** [starkoora/wanted-pre-onboarding-challenge-fe-1-api#4]
참조해주신 서버부분에 대한 설치가 끝났지만 localhost:8080 확인 결과 500error가 계속 뜨고 있어
의문이 생겨 문의드립니다 확인 한번만 부탁드리겠습니다 감사합니다

**Comment by starkoora** [comment]
@SeungMiL 프로젝트를 새로 클론 받아 실행 시켜보았으나 정상동작하는 것을 확인했습니다.
어떤 조건에서 에러가 발생하는지, 에러메시지는 구체적으로 무엇인지 알려주셔야 에러 재현 및 도움을 드릴 수 있을 것 같습니다.
<img width="455" alt="image" src="https://user-images.githubusercontent.com/109899564/181918644-a0c9eea6-0e06-4413-8460-db4ede060a0f.png">

**Comment by starkoora** [comment]
@SeungMiL 문서를 다시 살펴보니 실행 스크립트가 start가 아니라 dev로 되어 있었군요 ㅎㅎ..
yarn start로 실행해보셨는지 체크 부탁드려요

**Comment by SeungMiL** [comment]
![error](https://user-images.githubusercontent.com/89256060/182014611-7312b436-f094-4a82-88e0-9977bb069e75.png)
노드 버전은 16.16 이며 git clone으로 받아 yarn install로 패키지를 받았습니다. yarn start로 서버를 킨후 react(리액트 서버는 localhost:3000)에서 fetch로 localhost:8080으로 get 요청을 했으나 500 Internal Server Error을 받았습니다. localhost:8080으로 직접 들어가보니 같은 오류를 확인했으며 wireShark를 통해 서버통신을 확인했으나 통신하는데 있어서 겹치는 서버는 없었고 통신하는 과정에서의 오류는 보이지 않았습니다. 제가 놓친 부분이나 잘못된 방법으로 했을까요?ㅠㅠ

**Comment by starkoora** [comment]
@SeungMiL 브라우저에서 api 주소를 그대로 오픈하게 되시면 루트경로(`/`)로 GET 요청을 보내게 되는 것이기 때문에 api 스펙에 맞게 요청을 보내신게 아닙니다.
README에 작성해드린 api 스펙에 맞게(ex. GET `/todos`) 요청을 보내시면 될 것 같습니다.
코드에 문제가 있는 상황이 아니므로 issue는 close 하겠습니다 :)
