### ISSUE TITLE
Todo 관련 질문 있습니다.

### ISSUE THREAD

**Issue by Jang-oi** [starkoora/wanted-pre-onboarding-challenge-fe-1-api#5]
![image](https://user-images.githubusercontent.com/79916465/181919659-d2c80dea-7b53-4445-b18d-8838e186df3c.png)

1. 위 이미지에서 개별 Todo를 조회 순서에 따라 페이지 뒤로가기를 통하여 조회할 수 있도록 해주세요. 가 어떤 의미인지 이해가 잘 되질 않습니다... Todo 자세히 보는 페이지를 만들어서 페이지 뒤로가기를 하더라도 조회가 정상적으로 되야 된다는 건지 답변 부탁드립니다!

![image](https://user-images.githubusercontent.com/79916465/181919742-d8f42a9f-1c03-4fdc-a27d-48efbd27a75f.png)

2. todo create 진행 시 리턴 되는 데이터가 있다고 명시가 되어 있는데 생성이 정상적으로 진행을 하고 나서 리턴 받는 데이터는 빈 값으로 리턴이 되고, getTodos 할 경우엔 정상적으로 생성은 되어 있습니다. 확인 부탁드립니다!

**Comment by starkoora** [comment]
@Jang-oi 1. A 할일 -> B 할일 -> C 할일 순서대로 조회한 상태에서 페이지 뒤로가기를 했을 때 C -> B -> A 순으로 조회가 될 수 있도록 구현하면 된다는 의미입니다. 일반적인 웹 페이지 조회 시의 경험을 떠올려보시면 될 것 같습니다.
레이아웃 관련해서는 일반적인 메모 앱(에버노트, MacOS 기본 메모 어플)의 레이아웃을 생각해주시면 될 것 같은데, 앞서 올려주신 issue에서 말씀드렸듯 사전 과제의 목적이 채점에 있지는 않기 때문에 과제 가이드라인을 유연하게 해석해서 구현해주셔도 무방할 것 같습니다.

2. 해당 부분은 create 하는 api 로직에서 await가 누락된 부분이 있어서 해당 부분 수정하여 반영했습니다. pull 받아서 과제 이어가주시면 되겠습니다. 리포트 감사합니다 :)
