### ISSUE TITLE
회원가입/로그인 api 스펙 문의

### ISSUE THREAD

**Issue by ggsno** [starkoora/wanted-pre-onboarding-challenge-fe-1-api#6]
- 안녕하세요! api 관련 문의사항이 있어서 이슈 남깁니다.
- 스펙상에는 회원가입/로그인 POST 요청시 전달할 파라미터가 없는데 api코드상에는 있는 것 같아 문의 드립니다.
- 구현시 어떤 기준으로 만들면 될까요?

<img width="694" alt="image" src="https://user-images.githubusercontent.com/46833758/182008667-61579fba-778e-48bd-b3d6-091a39e9fff8.png">
<img width="451" alt="image" src="https://user-images.githubusercontent.com/46833758/182008735-fa4665c3-4573-469a-adf4-16e608909c88.png">

**Comment by starkoora** [comment]
@ggsno 문서에서 누락된 부분이니 기능 동작이 가능한 쪽으로 진행해주시면 됩니다. 해당 부분 README에 반영해두었습니다 :)
