### ISSUE TITLE
API 실행 관련 질문드립니다.

### ISSUE THREAD

**Issue by wjs5025** [starkoora/wanted-pre-onboarding-challenge-fe-1-api#7]
해당 레파지토리를 clone한 뒤, 
레파지토리 경로에서 
> npm i

그 다음 
Readme에 적혀 있는 대로,
> yarn
> yarn start
를 수행했는데, 

SyntaxError: Unexpected token '||='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)

에러와 함께 실행이 되지 않습니다. 제가 실행한 방법이 맞는지 확인 부탁 드리며 해결 방법을 알려주시면 감사하겠습니다 ㅠㅠ

**Comment by starkoora** [comment]
@wjs5025 node.js 버전이 낮아 해당 문법을 지원하지 못하는 상황으로 보입니다 node 16버전 이상으로 올리고 다시 시도해보시겠어요?
![image](https://user-images.githubusercontent.com/109899564/182310448-a5c76628-9368-44c9-95f0-6f2759826f86.png)
링크 : https://node.green/

**Comment by wjs5025** [comment]
감사합니다. node 버전 업그레이드 후 해결되었습니다.
