### ISSUE TITLE
API 호출 시 단순 fetch로는 불러 올 수 없는 걸까요?

### ISSUE THREAD

**Issue by jihoon8730** [starkoora/wanted-pre-onboarding-challenge-fe-1-api#8]
postman으로 확인이 가능하나 호출 시 400에러가 자꾸 나는데 이유가 있을까요?
<img width="512" alt="image" src="https://user-images.githubusercontent.com/88140865/183034102-57fe2200-c4de-48c0-a3bd-f2c84a17cb73.png">

<img width="334" alt="image" src="https://user-images.githubusercontent.com/88140865/183034207-bbddc621-e96c-4599-95b5-de7b0efd37fb.png">

**Comment by rnrn99** [comment]
```
headers: {
  "Content-Type": "application/json",
},
```
fetch 요청 옵션에 Content-Type 선언해주면 됩니다!

**Comment by jihoon8730** [comment]
감사합니다 덕분에 해결 했습니다!!
